services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    restart: always
    networks:
      - nginx_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro
      - /etc/pki/tls/certs/_.galco.com.chained.crt:/etc/nginx/certs/galco.com.crt
      - /etc/pki/tls/private/_.galco.com.key:/etc/nginx/certs/galco.com.key

volumes:
  conf:
  vhost:
  html:

networks:
  nginx_network:
    name: nginx_network
