services:
  nginx-proxy:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: nginx-proxy
    restart: always
    networks:
      - nginx_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./custom.conf:/etc/nginx/conf.d/custom.conf:ro

volumes:
  conf:
  vhost:
  html:

networks:
  nginx_network:
    name: nginx_network
